version: '3.8'

services:
  wa-throtle:
    build: .
    image: wa-throtle:latest
    container_name: wa-throtle
    restart: always
    ports:
      - "7000:7000"
    environment:
      - NODE_ENV=production
      # Use your CasaOS/Server IP here so it can find the other container
      - WHATSAPP_GO_URL=http://192.168.1.xxx:8080 
      - SEND_INTERVAL_MS=9000
      - PORT=7000